name: Python Workflow with Ubuntu-dependencies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repository
      - name: Clone repository
        uses: actions/checkout@v3

      # 2. Install Ubuntu-dependencies
      - name: Install Ubuntu-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libffi-dev python3-dev build-essential

      # 3. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 4. Install dependencies with pip
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install beeware briefcase toga --upgrade

      # 5. Run tests
      #- name: Run tests
      #  run: pytest
      - name: Build
        run: |
          briefcase package